setwd("C:/Users/shaya/Documents/VSCode/FSEM/FSEM")
options(width=200)
r <- readRDS("outputs/result_parameter_set1_regular.missing_1_N_100_M_20.rds")
cat("var$observed:", r$model.fit$var$observed, "\n")
cat("var names:", names(r$model.fit$var), "\n")
cat("hist names:", names(r$estimation$hist), "\n")
cat("hist.sem length:", length(r$estimation$hist$hist.sem), "\n")
cat("hist.sem[[1]] names:", names(r$estimation$hist$hist.sem[[1]]), "\n")
cat("has g.x:", !is.null(r$estimation$hist$hist.sem[[1]]$g.x), "\n")
cat("has g:", !is.null(r$estimation$hist$hist.sem[[1]]$g), "\n")
cat("deltaa/pen.sem present:", !is.null(r$estimation$hist$hist.sem[[1]]$deltaa), !is.null(r$estimation$hist$hist.sem[[1]]$pen.sem), "\n")
gx1 <- r$estimation$hist$hist.sem[[1]]$g.x[[1]]
cat("g.x[[1]] dim:", paste(dim(gx1),collapse="x"), "\n")
cat("g[[1]][[1]] dim:", paste(dim(r$estimation$hist$hist.sem[[1]]$g[[1]][[1]]),collapse="x"), "\n")
cat("sigma.sem[[1]] dim:", paste(dim(r$estimation$result$params.estimated$sigma.sem[[1]]),collapse="x"), "\n")
cat("gamma.param.x.std structure:\n"); str(r$estimation$result$params.estimated$gamma.param.x.std, max.level=2)
cat("\ncoef.sem.std org names:", names(r$simulation$params.org.eval$coef.sem.std$eta), "\n")
cat("regression covariate:", unlist(r$model.fit$mod$regression[[1]]$covariate), " effect:", unlist(r$model.fit$mod$regression[[1]]$effect), "\n")
cat("model.sim regression effect:", unlist(r$model.sim$mod$regression[[1]]$effect), "\n")
cat("eta.l[[1]][[1]] structure:\n"); str(r$estimation$hist$hist.fac[[1]]$eta.l[[1]][[1]], max.level=1)
