setwd("C:/Users/shaya/Documents/VSCode/FSEM/FSEM")
options(width=200)
f1 <- "outputs/result_parameter_set1_regular_1_N_50_M_10.rds"
r <- readRDS(f1)
cat("==== TOP NAMES of one result ====\n"); print(names(r))
cat("\n model.fit$var names:\n"); print(names(r$model.fit$var))
cat("indicators:", r$model.fit$var$indicators, "\n")
cat("latents:", r$model.fit$var$latents, "\n")
cat("factors:", r$model.fit$var$factors, "\n")
cat("n factorModel:", length(r$model.fit$mod$factorModel), " n regression:", length(r$model.fit$mod$regression), "\n")
cat("\n estimation names:\n"); print(names(r$estimation))
cat("\n params.estimated.eval names:\n"); print(names(r$estimation$result$params.estimated.eval))
cat("\n coef.fac.std structure:\n"); str(r$estimation$result$params.estimated.eval$coef.fac.std, max.level=2)
cat("\n sim params.org.eval names:\n"); print(names(r$simulation$params.org.eval))
cat("\n coef.fac.std ORG structure:\n"); str(r$simulation$params.org.eval$coef.fac.std, max.level=2)
cat("\n N ids:", length(unique(r$simulation$data$.id)), "\n")
cat("size MB:", round(file.size(f1)/1e6,1), "\n")
cat("has hist?", !is.null(r$estimation$hist), "\n")
